#!/bin/bash
# FIX THIS ISSUES | NON-ACUTE
#shellcheck disable=SC1091,SC2001,SC2015,SC2153,SC2154,SC2155,SC2181,SC2207


: 'ATTENTION!:
---------------------------------------------------
|  Created by danpaltor <danielpalumbi@gmail.com> |
|  Shellchecked by uniminin <uniminin@zoho.com>   |
---------------------------------------------------
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
------------------------------------------------------------------------
Run this script after your first boot with archlinux (as root)
'

if [[ -f $(pwd)/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "missing file: sharedfuncs"
  exit 1
fi


#ARCHLINUX INSTALL SCRIPTS MODE {{{

#select_keymap
if [[ -f $(pwd)/naisfunc/select_keymap ]]; then
  source naisfunc/select_keymap
else
  echo "missing file: select_keymap"
  exit 1
fi
#end select_keymap

#select_editor
if [[ -f $(pwd)/naisfunc/select_editor ]]; then
  source naisfunc/select_editor
else
  echo "missing file: select_editor"
  exit 1
fi
#end select_editor

#configure_mirrorlist
if [[ -f $(pwd)/naisfunc/configure_mirrorlist ]]; then
  source naisfunc/configure_mirrorlist
else
  echo "missing file: configure_mirrorlist"
  exit 1
fi
#end configure_mirrorlist

#umount_partitions
if [[ -f $(pwd)/naisfunc/umount_partitions ]]; then
  source naisfunc/umount_partitions
else
  echo "missing file: umount_partitions"
  exit 1
fi
#end umount_partitions

#select_device
if [[ -f $(pwd)/naisfunc/select_device ]]; then
  source naisfunc/select_device
else
  echo "missing file: select_device"
  exit 1
fi
#end select_device

#create_partition_scheme
if [[ -f $(pwd)/naisfunc/create_partition_scheme ]]; then
  source naisfunc/create_partition_scheme
else
  echo "missing file: create_partition_scheme"
  exit 1
fi
#end create_partition_scheme

#create_partition
if [[ -f $(pwd)/naisfunc/create_partition ]]; then
  source naisfunc/create_partition
else
  echo "missing file: create_partition"
  exit 1
fi
#end create_partition

#setup_luks
if [[ -f $(pwd)/naisfunc/setup_luks ]]; then
  source naisfunc/setup_luks
else
  echo "missing file: setup_luks"
  exit 1
fi
#end setup_luks

#setup_lvm
if [[ -f $(pwd)/naisfunc/setup_lvm ]]; then
  source naisfunc/setup_lvm
else
  echo "missing file: setup_lvm"
  exit 1
fi
#end setup_lvm

#format_partitions
if [[ -f $(pwd)/naisfunc/format_partitions ]]; then
  source naisfunc/format_partitions
else
  echo "missing file: format_partitions"
  exit 1
fi
#end format_partitions

#select_linux_version
if [[ -f $(pwd)/naisfunc/select_linux_version ]]; then
  source naisfunc/select_linux_version
else
  echo "missing file: select_linux_version"
  exit 1
fi
#end select_linux_version

#install_base_system
if [[ -f $(pwd)/naisfunc/install_base_system ]]; then
  source naisfunc/install_base_system
else
  echo "missing file: install_base_system"
  exit 1
fi
#end install_base_system

#configure_keymap
if [[ -f $(pwd)/naisfunc/configure_keymap ]]; then
  source naisfunc/configure_keymap
else
  echo "missing file: configure_keymap"
  exit 1
fi
#end configure_keymap

#configure_fstab
if [[ -f $(pwd)/naisfunc/configure_fstab ]]; then
  source naisfunc/configure_fstab
else
  echo "missing file: configure_fstab"
  exit 1
fi
#end configure_fstab

#configure_hostname
if [[ -f $(pwd)/naisfunc/configure_hostname ]]; then
  source naisfunc/configure_hostname
else
  echo "missing file: configure_hostname"
  exit 1
fi
#end configure_hostname

#configure_timezone
if [[ -f $(pwd)/naisfunc/configure_timezone ]]; then
  source naisfunc/configure_timezone
else
  echo "missing file: configure_timezone"
  exit 1
fi
#end configure_timezone

#configure_hardwareclock
if [[ -f $(pwd)/naisfunc/configure_hardwareclock ]]; then
  source naisfunc/configure_hardwareclock
else
  echo "missing file: configure_hardwareclock"
  exit 1
fi
#end configure_hardwareclock

#configure_locale
if [[ -f $(pwd)/naisfunc/configure_locale ]]; then
  source naisfunc/configure_locale
else
  echo "missing file: configure_locale"
  exit 1
fi
#end configure_locale

#configure_mkinitcpio
if [[ -f $(pwd)/naisfunc/configure_mkinitcpio ]]; then
  source naisfunc/configure_mkinitcpio
else
  echo "missing file: configure_mkinitcpio"
  exit 1
fi
#end configure_mkinitcpio

#install_bootloader
if [[ -f $(pwd)/naisfunc/install_bootloader ]]; then
  source naisfunc/install_bootloader
else
  echo "missing file: install_bootloader"
  exit 1
fi
#end install_bootloader

#configure_bootloader
if [[ -f $(pwd)/naisfunc/configure_bootloader ]]; then
  source naisfunc/configure_bootloader
else
  echo "missing file: configure_bootloader"
  exit 1
fi
#end configure_bootloader

#root_password
if [[ -f $(pwd)/naisfunc/root_password ]]; then
  source naisfunc/root_password
else
  echo "missing file: root_password"
  exit 1
fi
#end root_password

#finish
if [[ -f $(pwd)/naisfunc/finish ]]; then
  source naisfunc/finish
else
  echo "missing file: finish"
  exit 1
fi
#end finish


pause_function
check_boot_system
check_connection
check_trim
pacman -Sy
while true; do
  print_title "NEW ARCHLINUX INSTALLER - https://github.com/danpaltor/nai"
  echo " 1) $(mainmenu_item "${checklist[1]}" "Select Keymap" "${KEYMAP}")"
  echo " 2) $(mainmenu_item "${checklist[2]}" "Select Editor" "${EDITOR}")"
  echo " 3) $(mainmenu_item "${checklist[3]}" "Configure Mirrorlist" "${country_name} (${country_code})")"
  echo " 4) $(mainmenu_item "${checklist[4]}" "Partition Scheme" "${partition_layout}: ${partition}(${filesystem}) swap(${swap_type})")"
  echo " 5) $(mainmenu_item "${checklist[5]}" "Install Base System")"
  echo " 6) $(mainmenu_item "${checklist[6]}" "Configure Fstab" "${fstab}")"
  echo " 7) $(mainmenu_item "${checklist[7]}" "Configure Hostname" "${host_name}")"
  echo " 8) $(mainmenu_item "${checklist[8]}" "Configure Timezone" "${ZONE}/${SUBZONE}")"
  echo " 9) $(mainmenu_item "${checklist[9]}" "Configure Hardware Clock" "${hwclock}")"
  echo "10) $(mainmenu_item "${checklist[10]}" "Configure Locale" "${LOCALE}")"
  echo "11) $(mainmenu_item "${checklist[11]}" "Configure Mkinitcpio")"
  echo "12) $(mainmenu_item "${checklist[12]}" "Install Bootloader" "${bootloader}")"
  echo "13) $(mainmenu_item "${checklist[13]}" "Root Password")"
  echo ""
  echo " d) Done"
  echo ""
  read_input_options
  for OPT in "${OPTIONS[@]}"; do
    case "$OPT" in
    1)
      select_keymap
      checklist[1]=1
      ;;
    2)
      select_editor
      checklist[2]=1
      ;;
    3)
      configure_mirrorlist
      checklist[3]=1
      ;;
    4)
      umount_partitions
      create_partition_scheme
      format_partitions
      checklist[4]=1
      ;;
    5)
      install_base_system
      configure_keymap
      checklist[5]=1
      ;;
    6)
      configure_fstab
      checklist[6]=1
      ;;
    7)
      configure_hostname
      checklist[7]=1
      ;;
    8)
      configure_timezone
      checklist[8]=1
      ;;
    9)
      configure_hardwareclock
      checklist[9]=1
      ;;
    10)
      configure_locale
      checklist[10]=1
      ;;
    11)
      configure_mkinitcpio
      checklist[11]=1
      ;;
    12)
      install_bootloader
      configure_bootloader
      checklist[12]=1
      ;;
    13)
      root_password
      checklist[13]=1
      ;;
    "d")
      finish
      ;;
    *)
      invalid_option
      ;;
    esac
  done
done
#}}}

