#!/bin/bash

#SETUP PARTITION{{{
create_partition() {
  apps_list=("cfdisk" "cgdisk" "fdisk" "gdisk" "parted")
  PS3="$prompt1"
  echo -e "Select partition program:"
  select OPT in "${apps_list[@]}"; do
    if contains_element "$OPT" "${apps_list[@]}"; then
      select_device
      case $OPT in
      parted)
        parted -a opt "${device}"
        ;;
      *)
        $OPT "${device}"
        ;;
      esac
      break
    else
      invalid_option
    fi
  done
}
#}}}
